name: kitify
version: 0.0.1.2
summary: All-in-one tools, boosting your efficiency!
description: All-in-one tools, boosting your efficiency!
icon: snap/gui/kitify.png
title: Kitify
contact: support@kitifylabs.com
license: GPL-3.0-only
source-code: https://github.com/kitifylabs/kitify
issues: https://github.com/kitifylabs/kitify/issues
website: https://www.kitifylabs.com
architectures:
  - build-on: [amd64]
  - build-on: [arm64]
confinement: strict
base: core22
grade: stable
slots:
  dbus-kitify: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.kitifylabs.Kitify # adjust accordingly to your app name and
apps:
  kitify:
    command: kitify
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - home
    slots:
      - dbus-kitify
parts:
  kitify:
    source: .
    plugin: flutter
    # flutter-target: lib/main.dart # The main entry-point file of the application
    build-packages:
      - curl
      - libcurl4-openssl-dev
      - git
      - unzip
      - xz-utils
      - zip
      - libglu1-mesa
      - clang
      - cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libstdc++-12-dev
    build-environment:
      - FLUTTER_REPO: https://github.com/flutter/flutter.git
      - FLUTTER_VERSION: 3.27.3
      - FLUTTER_TARGET: lib/main_free.dart
    override-build: |
      # https://github.com/canonical/snapcraft/blob/main/snapcraft/parts/plugins/flutter_plugin.py
      KTY_FLUTTER_BUILD_DIR="$CRAFT_PART_BUILD/flutter-distro"
      if [ -d "$KTY_FLUTTER_BUILD_DIR" ]; then
        echo "$KTY_FLUTTER_BUILD_DIR"
        rm -rf $KTY_FLUTTER_BUILD_DIR
      fi
      git clone --depth 1 -b $FLUTTER_VERSION $FLUTTER_REPO $KTY_FLUTTER_BUILD_DIR
      flutter doctor -v
      flutter precache --linux
      flutter pub get
      flutter build linux --release --dart-define-from-file=.env --target $FLUTTER_TARGET
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
